name: CI

on:
  push:
    branches: [ "projeto-base" ]
  pull_request:

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Tenta listar arquivos antes do `actions/checkout@v3`
        run: ls -la

      - uses: actions/checkout@v3

      - name: Lista arquivos após `actions/checkout@v3`
        run: ls -la
          
      - run: echo Olá mundo!
